### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by Shalynishka** [greadvx/tistic.co#1]
Пункт 2.4 
Не рекомендуется использовать требования с отрицаниями, это противоречит недвусмысленности требований. 
Пункт 3.2.3
Структура хранения информации в JSON файлах имеет отношение к архитектуре, а не к требованиям.

**Comment by greadvx** [comment]
Комментарий обоснован. Замечания учтены. 
Пункт [2.4. Assumptions and Dependencies](
https://github.com/greadvx/tistic.co/blob/master/docs/Requirements.md#2.4) и пункт [3.2.3. Constraints](
https://github.com/greadvx/tistic.co/blob/master/docs/Requirements.md#3.2.3) исправлены.
